"""Update plan features to JSON and sync plan types

Revision ID: 17f061e6d6dd
Revises: initial
Create Date: 2025-12-12 21:15:30.154351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f061e6d6dd'
down_revision: Union[str, None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plans', 'type',
               existing_type=postgresql.ENUM('FREE', 'PRO', 'TEAM', 'CAMPUS', name='plantype'),
               nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'features',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='features::json')
    op.drop_constraint('plans_name_key', 'plans', type_='unique')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('plans_name_key', 'plans', ['name'])
    op.alter_column('plans', 'features',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'type',
               existing_type=postgresql.ENUM('FREE', 'PRO', 'TEAM', 'CAMPUS', name='plantype'),
               nullable=False)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###