"""Add payments table and update invoices

Revision ID: 3805fb581fe2
Revises: 5d67958dfc9b
Create Date: 2025-12-12 21:52:19.562249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3805fb581fe2'
down_revision: Union[str, None] = '5d67958dfc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('provider_order_id', sa.String(), nullable=True),
    sa.Column('payment_method_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('invoices', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.drop_constraint('invoices_razorpay_payment_id_key', 'invoices', type_='unique')
    op.drop_constraint('invoices_stripe_invoice_id_key', 'invoices', type_='unique')
    op.create_foreign_key(None, 'invoices', 'payments', ['payment_id'], ['id'])
    op.drop_column('invoices', 'stripe_invoice_id')
    op.drop_column('invoices', 'razorpay_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('stripe_invoice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_unique_constraint('invoices_stripe_invoice_id_key', 'invoices', ['stripe_invoice_id'])
    op.create_unique_constraint('invoices_razorpay_payment_id_key', 'invoices', ['razorpay_payment_id'])
    op.drop_column('invoices', 'payment_id')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###