"""fix enum values

Revision ID: 685edcbcaded
Revises: 17f061e6d6dd
Create Date: 2025-12-12 21:17:45.797494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685edcbcaded'
down_revision: Union[str, None] = '17f061e6d6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE plantype ADD VALUE IF NOT EXISTS 'STARTER'")
    op.execute("ALTER TYPE plantype ADD VALUE IF NOT EXISTS 'ENTERPRISE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###