"""Remove stripe_price_id from plans

Revision ID: 83ba5154bc83
Revises: 685edcbcaded
Create Date: 2025-12-12 21:19:24.194525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ba5154bc83'
down_revision: Union[str, None] = '685edcbcaded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'stripe_price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###