"""Add razorpay_order_id and plan_id to Invoice

Revision ID: e30f9a633ad4
Revises: 9e9e8e010042
Create Date: 2025-12-14 13:51:01.436120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30f9a633ad4'
down_revision: Union[str, None] = '9e9e8e010042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'plan_id')
    op.drop_column('invoices', 'razorpay_order_id')
    # ### end Alembic commands ###